### PR TITLE
Allow numeric endpoint

### PR DESCRIPTION
**Pull request by DyegoCosta**

### CODE REVIEW

**Comment by burabure** [comment]
Nice!, could you add a smal test for this case?

**Comment by DyegoCosta** [comment]
@burabure another one? https://github.com/springboardretail/api-operations/pull/1/files#diff-6e3916922d79a871b232c86b96e79672R336

**Comment by burabure** [comment]
Whoops, missed it. Code reviewing in a phone is hard XD. Pushing this to npm when I get back home from the doc

**Comment by burabure** [comment]
published!

**Pull request merged**
